config/routes.rb
Rails.application.routes.draw do
  root "articles#index"
  devise_for :users
  resources :users, only: :show
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_one_attached :avatar
  has_many :articles
  validates :nickname, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname,:avatar,:profile_text,:background_image])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname,:avatar,:profile_text,:background_image])
    # devise_parameter_sanitizer.permit(:sign_up, keys: [:avatar])
    # devise_parameter_sanitizer.permit(:sign_up, keys: [:profile_text])

  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!,except: :index
  
  def index

    @articles = Article.includes(:user).page(params[:page]).per(10).order("created_at DESC")
  end

  def new
    @article = Article.new
  end

  def create
    Article.create(article_params)
    redirect_to action: :index
  end

  def show
    @article = Article.find(params[:id])
    # agent = Mechanize.new
    # # page = agent.get("http://localhost:3000/articles/#{@article.id}")
    # text_a_url = @article.text.search('a').get_attribute('href')
    # @image = agent.get("#{text_a_url}").at('img')
    # @url_text_h1 = agent.get("#{text_a_url}").at('h1').inner_text

  end

  def edit
    @article = Article.find(params[:id]) 
  end

  def update
    article = Article.find(params[:id])
    article.update(article_params) if article.user_id == current_user.id
    redirect_to action: :index
  end

  def destroy
    article = Article.find(params[:id])
    article.destroy if article.user_id == current_user.id
    redirect_to action: :index
  end

  private
  def article_params
    params.require(:article).permit(:text).merge(user_id: current_user.id)
  end

  def move_to_index
    redirect_to action: :index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @articles = @user.articles.page(params[:page]).per(10).order("created_at DESC")
    @article.text = view_context.auto_link(@article.text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  require "uri"

  def text_url_to_link text

    URI.extract(text, ['http','https']).uniq.each do |url|
      sub_text = ""
      sub_text << "<a href=" << url << " target=\"_blank\">" << url << "</a>"

      text.gsub!(url, sub_text)
    end

    return text
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/edit.html.erb
<div class="new_header">
  <h2>新規投稿を追加</h2>
</div>
<div class="container">
  <div class="post_area">
    <%= form_for @article, :url => {:action => 'update'} do |f| %>
    <div class="center">
      <p>投稿内容</p>
      <%= f.text_area :text, placeholder: "こちらに記事をお書きください", class: "post_text_field" %>
    </div>
    <div class="center">
      <%= f.submit "ツイート", class: "tweet_btn" %>
      <%= link_to "キャンセル", root_path, class: "btn" %>
    </div>
    <% end %>
  </div>
</div>

app/views/articles/new.html.erb
<div class="new_header">
  <h2>新規投稿を追加</h2>
</div>
<div class="container">
  <div class="post_area">
    <%= form_for @article do |f| %>
    <div class="center">
      <p>投稿内容</p>
      <%= f.text_area :text,placeholder: "こちらに記事をお書きください", class: "post_text_field" %>
    </div>
    <div class="center">
      <%= f.submit "ツイート", class: "tweet_btn" %>
      <%= link_to "キャンセル", root_path, class: "btn" %>
    </div>
    <% end %>
  </div>
</div>

app/views/articles/show.html.erb
<div class="contents container clearfix" >
  <div class="left_content">
    <% if user_signed_in?%>
      <div class="user_background">
        <%= image_tag current_user.background_image,class:"user_background" %>
      </div>
      <div class="user_info clearfix">
        
        <%= image_tag current_user.avatar, class:"user_avatar" %>
        
        <%= link_to 'プロフィールの編集', edit_user_registration_path, class:"profile_edit" %>
      </div>
      <div class="user_profile">
          <h2><a href=""><%= current_user.nickname %></a></h2>
          <div class="user_profile_text">
            <%= current_user.profile_text %>
          </div>
      </div>
    <% end %>
  </div>

  <div class="right_content">
    <%= render partial: "shared/article" , locals: { article: @article }%>
    

  </div>
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="discription" content="">
    <meta name="Viewport" content="widht=device-width,initial-scale=1">
    <link rel="stylesheet" href="normalize.css">
    <link rel="stylesheet" href="css/styles.css">
    <link rel="shortcut icon" href="favicon.ico">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <title>BlogTemp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header clearfix">
      <div class="container" class="clearfix">
        <%= link_to 'Logo', root_path, method: :get, class: "logo"%>
        <ul class="clearfix">
        <% if user_signed_in? %>
          <li><%= link_to "#{current_user.nickname}","/users/#{current_user.id}",class:"header_link_text" %></li>
          <li><i class="fas fa-pen"></i><%= link_to ' 投稿', new_article_path, method: :get, class: "header_link_text" %></li>
          <li><%= link_to 'ログアウト', "/users/sign_out", method: :delete, class: "header_link_text" %></li>
        <% else%>
          <li><i class="fas fa-pen"></i><%= link_to ' 投稿', new_article_path, method: :get, class: "header_link_text" %></li>
          <li><%= link_to 'ログイン', "/users/sign_in", method: :get, class: "header_link_text" %></li>
        <% end %>
        </ul>
      </div>
    </header>
    <%= yield %>
    <footer>
      <div class="container">
        <p>&copy:mylevel</p>
      </div>
    </footer>
  </body>
</html>

app/views/shared/_article.html.erb
<article class="clearfix post_article">
  <%= image_tag article.user.avatar, class:"post_user_img" %>
    <nav id="menu" role="navigation">
        <ul>
          <li class="child-list"><i class="fas fa-caret-down"></i>
            <ul class="sub-menu">
              <li><%= link_to '編集',"/articles/#{article.id}/edit",method: :get,class:"sub_menu_list" %></li>
              <li><%= link_to '削除',"/articles/#{article.id}",method: :delete,class:"sub_menu_list" %></li>
            </ul>
          </li>
        </ul>
      </nav>
  <div class="post_text">
    <%= link_to "#{article.user.nickname}","/users/#{article.user.id}",class:"post_user" %>
    <% if article.text.include?("http") %>
      <div class="posted_text_area">
        <%= text_url_to_link(h(simple_format(article.text))).html_safe %>
      </div>
      <div>
        これが出てくればOK
        <%= @image %>
        <%= @url_text_h1 %>
      </div>
    <% else %>
      <%= text_url_to_link(h(simple_format(article.text))).html_safe %>
    <% end %>
  </div>
</article>

app/views/users/show.html.erb
<div class="contents container clearfix" >
  <div class="left_content">
    <% if user_signed_in?%>
      <div class="user_background">
        <%= image_tag current_user.background_image,class:"user_background" %>
      </div>
      <div class="user_info clearfix">
        
        <%= image_tag current_user.avatar, class:"user_avatar" %>
        
        <%= link_to 'プロフィールの編集', edit_user_registration_path, class:"profile_edit" %>
      </div>
      <div class="user_profile">
          <h2><%= link_to "#{current_user.nickname}","/users/#{current_user.id}" %></h2>
          <div class="user_profile_text">
            <%= current_user.profile_text %>
          </div>
      </div>
    <% end %>
  </div>

  <div class="right_content">
    <div class="user_background">
      <%= image_tag current_user.background_image,class:"user_background" %>
    </div>
    <div class="user_info clearfix">
        
      <%= image_tag current_user.avatar, class:"user_avatar" %>
    </div>
    <div class="user_profile">
        <h2><%= link_to "#{@user.nickname}","/users/#{@user.id}" %></h2>
        <div class="user_profile_text">
          <%= @user.profile_text %>
        </div>
    </div>
    <% @articles.each do |article| %>
      <div class="post_shown_link_area">
        <%= render partial: "shared/article" , locals: { article: article }%>
        <%= link_to "","/articles/#{article.id}",method: :get, class:"post_shown_link" %>
      </div>
    <% end %>
    
    <%= paginate(@articles) %>
    

  </div>
  
</div>